"""users accounts portfolios sections assets analytics

Revision ID: daa140e0d425
Revises: 
Create Date: 2026-09-03 21:46:35.644500
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'daa140e0d425'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('account_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=False),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('privacy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('google_linked', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_step_secret', sa.String(length=64), nullable=True),
    sa.Column('two_step_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_step_pending_secret', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('free', 'pro')", name=op.f('ck_account_settings_plan_is_known')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_account_settings_user_id'))
    )
    op.create_table('assets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'file')", name=op.f('ck_assets_kind_is_known')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_assets_byte_size_is_not_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index('ix_assets_user_id_sha256', 'assets', ['user_id', 'sha256'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=120), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_auth_sessions_user_id_revoked_at', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=24), nullable=False),
    sa.Column('accent', sa.String(length=32), nullable=False),
    sa.Column('ground', sa.String(length=16), nullable=False),
    sa.Column('font', sa.String(length=24), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("font IN ('archivo', 'fraunces', 'space-grotesk')", name=op.f('ck_portfolios_font_is_known')),
    sa.CheckConstraint("ground IN ('light', 'dark', 'paper')", name=op.f('ck_portfolios_ground_is_known')),
    sa.CheckConstraint("status IN ('live', 'draft', 'empty')", name=op.f('ck_portfolios_status_is_known')),
    sa.CheckConstraint("theme IN ('editorial', 'index', 'poster', 'links', 'ledger', 'dossier', 'broadsheet')", name=op.f('ck_portfolios_theme_is_known')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_index(op.f('ix_portfolios_slug'), 'portfolios', ['slug'], unique=True)
    op.create_index('ix_portfolios_user_id_created_at', 'portfolios', ['user_id', 'created_at'], unique=False)
    op.create_table('recovery_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_table('account_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portrait_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portrait_asset_id'], ['assets.id'], name=op.f('fk_account_profiles_portrait_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_profiles')),
    sa.UniqueConstraint('handle', name=op.f('uq_account_profiles_handle')),
    sa.UniqueConstraint('user_id', name=op.f('uq_account_profiles_user_id'))
    )
    op.create_table('link_clicks',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_link_clicks_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_clicks'))
    )
    op.create_index(op.f('ix_link_clicks_occurred_at'), 'link_clicks', ['occurred_at'], unique=False)
    op.create_index('ix_link_clicks_portfolio_id_occurred_at', 'link_clicks', ['portfolio_id', 'occurred_at'], unique=False)
    op.create_table('page_views',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('referrer_host', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_page_views_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_views')),
    sa.UniqueConstraint('portfolio_id', 'dedupe_key', name='uq_page_views_portfolio_id_dedupe')
    )
    op.create_index(op.f('ix_page_views_occurred_at'), 'page_views', ['occurred_at'], unique=False)
    op.create_index('ix_page_views_portfolio_id_occurred_at', 'page_views', ['portfolio_id', 'occurred_at'], unique=False)
    op.create_table('portfolio_headers',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portrait_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_headers_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portrait_asset_id'], ['assets.id'], name=op.f('fk_portfolio_headers_portrait_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_headers')),
    sa.UniqueConstraint('portfolio_id', name=op.f('uq_portfolio_headers_portfolio_id'))
    )
    op.create_table('sections',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('image_asset_id', sa.UUID(), nullable=True),
    sa.Column('file_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('link', 'venture', 'contact', 'booking', 'testimonial', 'gallery', 'numbers', 'document')", name=op.f('ck_sections_kind_is_known')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_sections_position_is_not_negative')),
    sa.ForeignKeyConstraint(['file_asset_id'], ['assets.id'], name=op.f('fk_sections_file_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['assets.id'], name=op.f('fk_sections_image_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_sections_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_index('ix_sections_portfolio_id_position', 'sections', ['portfolio_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sections_portfolio_id_position', table_name='sections')
    op.drop_table('sections')
    op.drop_table('portfolio_headers')
    op.drop_index('ix_page_views_portfolio_id_occurred_at', table_name='page_views')
    op.drop_index(op.f('ix_page_views_occurred_at'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index('ix_link_clicks_portfolio_id_occurred_at', table_name='link_clicks')
    op.drop_index(op.f('ix_link_clicks_occurred_at'), table_name='link_clicks')
    op.drop_table('link_clicks')
    op.drop_table('account_profiles')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_index('ix_portfolios_user_id_created_at', table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_slug'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_auth_sessions_user_id_revoked_at', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_assets_user_id_sha256', table_name='assets')
    op.drop_table('assets')
    op.drop_table('account_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
