"""widen slug for nested addresses

Revision ID: e576c2f5da41
Revises: daa140e0d425
Create Date: 2026-09-03 22:09:06.637505
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e576c2f5da41'
down_revision: str | None = 'daa140e0d425'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'slug',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
